# Generated by Django 4.2 on 2023-07-05 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeWorker',
            fields=[
                ('CafeWorkID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('CafeWorkName', models.TextField(max_length=255)),
                ('CafeWorkPhone', models.CharField(max_length=11)),
                ('CafeWorkPass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuID', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('MenuName', models.TextField(max_length=255)),
                ('MenuPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudID', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('StudName', models.TextField(max_length=255)),
                ('StudPhone', models.CharField(max_length=11)),
                ('StudPass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FoodBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quant', models.IntegerField(default=1)),
                ('Status', models.CharField(default='Request Pending', max_length=128)),
                ('CafeWorkID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ForkAndBook.cafeworker')),
                ('MenuID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ForkAndBook.menu')),
                ('StudID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ForkAndBook.student')),
            ],
        ),
    ]
