# Generated by Django 4.2 on 2023-07-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForkAndBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeWorker',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='CafeWorkID',
            new_name='EmployeeID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='CafeWorkName',
            new_name='EmployeeName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='CafeWorkPass',
            new_name='EmployeePass',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='CafeWorkPhone',
            new_name='EmployeePhone',
        ),
        migrations.RenameField(
            model_name='foodbook',
            old_name='CafeWorkID',
            new_name='EmployeeID',
        ),
    ]
