# Generated by Django 4.2 on 2023-07-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForkAndBook', '0002_rename_cafeworker_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='EmployeeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ForkAndBook.employee'),
        ),
    ]
